//@flow
export const FETCH_VALUE = "FETCH_VALUE";

export const FETCHING_DATA = "FETCHING_DATA";
export const FETCHING_DATA_SUCCESS = "FETCHING_DATA_SUCCESS";
export const FETCHING_DATA_FAILURE = "FETCHING_DATA_FAILURE";

export const FETCH_REPOSITORIES_REQUEST = "FETCH_REPOSITORIES_REQUEST";
export const FETCH_REPOSITORIES_SUCCESS = "FETCH_REPOSITORIES_SUCCESS";
export const FETCH_REPOSITORIES_FAILURE = "FETCH_REPOSITORIES_FAILURE";

export const USER_TYPING = "USER_TYPING";

export const CAPITALIZED_ERROR_CHANGE = "CAPITALIZED_ERROR_CHANGE";

export const ITEM_SELECTED = "ITEM_SELECTED";
export const ITEM_UNSELECTED = "ITEM_UNSELECTED";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const RECENT_SEARCH_ITEM_CLICKED = "RECENT_SEARCH_ITEM_CLICKED";
export const CLEAR_REPOSITORIES_LIST = "CLEAR_REPOSITORIES_LIST";